// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdOEmBbHICgXmj2YRWOoapKGsFPsf9Yas',
    appId: '1:749809337898:web:46ba7289eb91252278e553',
    messagingSenderId: '749809337898',
    projectId: 'dsclimasyrefrigeracion-dfd60',
    authDomain: 'dsclimasyrefrigeracion-dfd60.firebaseapp.com',
    storageBucket: 'dsclimasyrefrigeracion-dfd60.firebasestorage.app',
    measurementId: 'G-ZV5S7JG1NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhNq20r4iB02F_FYaTQkHSFRyIcc4N-bA',
    appId: '1:749809337898:android:cc55349975caaa2f78e553',
    messagingSenderId: '749809337898',
    projectId: 'dsclimasyrefrigeracion-dfd60',
    storageBucket: 'dsclimasyrefrigeracion-dfd60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTE8QhppovD4ToJeMw8LgruWU8WJVEB5Q',
    appId: '1:749809337898:ios:03c0827d85fea05d78e553',
    messagingSenderId: '749809337898',
    projectId: 'dsclimasyrefrigeracion-dfd60',
    storageBucket: 'dsclimasyrefrigeracion-dfd60.firebasestorage.app',
    iosBundleId: 'com.example.gestionDsClimas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTE8QhppovD4ToJeMw8LgruWU8WJVEB5Q',
    appId: '1:749809337898:ios:03c0827d85fea05d78e553',
    messagingSenderId: '749809337898',
    projectId: 'dsclimasyrefrigeracion-dfd60',
    storageBucket: 'dsclimasyrefrigeracion-dfd60.firebasestorage.app',
    iosBundleId: 'com.example.gestionDsClimas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdOEmBbHICgXmj2YRWOoapKGsFPsf9Yas',
    appId: '1:749809337898:web:ef39473a843eaa0278e553',
    messagingSenderId: '749809337898',
    projectId: 'dsclimasyrefrigeracion-dfd60',
    authDomain: 'dsclimasyrefrigeracion-dfd60.firebaseapp.com',
    storageBucket: 'dsclimasyrefrigeracion-dfd60.firebasestorage.app',
    measurementId: 'G-WJV3EHK09K',
  );
}
